/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Gestion.GestionCitas;
import Gestion.GestionConsultorios;
import Gestion.GestionEmpleados;
import Gestion.GestionFacturacion;
import Modelo.Empleado;
import GUI.EmpleadosGestionPanel;
import GUI.ConsultoriosGestionPanel;

/**
 *
 * @author erick
 */
public class AdminPanel extends javax.swing.JPanel {
    
    private MainFrame mainFrame;
    private GestionEmpleados gestionEmpleados;
    private GestionConsultorios gestionConsultorios;
    private GestionCitas gestionCitas;
    private GestionFacturacion gestionFacturacion;
    private final Empleado administrador;
    
    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        this(null, null, null, null, null, null); 
    }
    
    public AdminPanel(MainFrame mainFrame, 
                      GestionEmpleados gestionEmpleados, 
                      GestionConsultorios gestionConsultorios, 
                      GestionCitas gestionCitas, 
                      GestionFacturacion gestionFacturacion,
                      Empleado administrador) {
        
        this.mainFrame = mainFrame;
        this.gestionEmpleados = gestionEmpleados;
        this.gestionConsultorios = gestionConsultorios;
        this.gestionCitas = gestionCitas;
        this.gestionFacturacion = gestionFacturacion;
        this.administrador = administrador;
        
        initComponents();
        
        EmpleadosGestionPanel empleadosPanel = new EmpleadosGestionPanel(gestionEmpleados);
        ConsultoriosGestionPanel consultoriosPanel = new ConsultoriosGestionPanel(gestionConsultorios);
        ReportesPanel reportesPanel = new ReportesPanel(gestionConsultorios, gestionCitas, gestionFacturacion, gestionEmpleados) ;
        tabbedPane.addTab("Gestionar Empleados", empleadosPanel);
        tabbedPane.addTab("Gestionar Consultorios", consultoriosPanel);
        tabbedPane.addTab("Reportes", reportesPanel);
        jLabel1.setText("Bienvenido, " + administrador.getNombres() + " (" + administrador.getRolEmpleado() + ")");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tabbedPane = new javax.swing.JTabbedPane();
        logoutButton = new java.awt.Button();

        setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Bienvenido");

        logoutButton.setLabel("Cerrar Sesion");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(250, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabbedPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        mainFrame.mostrarLoginPanel();
    }//GEN-LAST:event_logoutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private java.awt.Button logoutButton;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
