/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Gestion.GestionCitas;
import Modelo.Cita;
import Modelo.EstadoCita;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author erick
 */
public class AdmisionPanel extends javax.swing.JPanel {
    private GestionCitas gestionCitas;
    private DefaultTableModel tableModel;
    private ArrayList<Cita> citasCargadas;
    /**
     * Creates new form AdmisionPanel
     */
    public AdmisionPanel() {
        this(null);
    }
    
    public AdmisionPanel(GestionCitas gestionCitas) {
        this.gestionCitas = gestionCitas;
        initComponents();
        
        String[] columnas = {"Hora", "Paciente", "Médico", "Consultorio", "Estado"};
        tableModel = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) { return false; }
        };
        tablaCitasDia.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fechaField = new javax.swing.JTextField();
        verCitasButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCitasDia = new javax.swing.JTable();
        registrarLlegadaButton = new javax.swing.JButton();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("Admision de Pacientes (Check-in)");

        jLabel2.setText("Ver citas para la fecha (yyyy/mm/dd): ");

        fechaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaFieldActionPerformed(evt);
            }
        });

        verCitasButton.setText("Ver Citas");
        verCitasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCitasButtonActionPerformed(evt);
            }
        });

        tablaCitasDia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaCitasDia);

        registrarLlegadaButton.setText("Registrar Llegada (Check-in)");
        registrarLlegadaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarLlegadaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fechaField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(verCitasButton)))
                        .addGap(0, 585, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(407, 407, 407)
                .addComponent(registrarLlegadaButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fechaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verCitasButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrarLlegadaButton)
                .addContainerGap(7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fechaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaFieldActionPerformed
    
    private void cargarCitasDelDia() {
        String fecha = fechaField.getText();
        if (fecha == null || fecha.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, introduzca una fecha.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        citasCargadas = gestionCitas.buscarCitaPorFecha(fecha.trim());
        
        tableModel.setRowCount(0);
        ArrayList<Cita> citasParaMostrar = new ArrayList<>();
        for (Cita cita : citasCargadas) {
            if (cita.getEstado() == EstadoCita.PROGRAMADA || cita.getEstado() == EstadoCita.CONFIRMADA || cita.getEstado() == EstadoCita.EN_SALA) {
                citasParaMostrar.add(cita);
                Object[] row = {
                    cita.getFechaHora().substring(11), // Extraer solo la hora
                    cita.getPaciente(),
                    cita.getMedico(),
                    cita.getConsultorio().getCodigo(),
                    cita.getEstado()
                };
                tableModel.addRow(row);
            }
        }
        citasCargadas = citasParaMostrar;
    }
    
    private void registrarLlegadaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarLlegadaButtonActionPerformed
        int selectedRow = tablaCitasDia.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una cita para registrar la llegada del paciente.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Cita citaSeleccionada = citasCargadas.get(selectedRow);

        if (citaSeleccionada.getEstado() == EstadoCita.EN_SALA) {
            JOptionPane.showMessageDialog(this, "El paciente ya ha sido admitido.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Confirmar la llegada del paciente " + citaSeleccionada.getPaciente().getNombres() + "?",
                "Confirmar Check-in",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            citaSeleccionada.setEstado(EstadoCita.EN_SALA);
            JOptionPane.showMessageDialog(this, "Check-in realizado. El paciente está en sala de espera.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            cargarCitasDelDia(); // Refrescar la tabla
        }
    }//GEN-LAST:event_registrarLlegadaButtonActionPerformed

    private void verCitasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCitasButtonActionPerformed
        cargarCitasDelDia();
    }//GEN-LAST:event_verCitasButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fechaField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    private javax.swing.JButton registrarLlegadaButton;
    private javax.swing.JTable tablaCitasDia;
    private javax.swing.JButton verCitasButton;
    // End of variables declaration//GEN-END:variables
}
