/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Gestion.GestionCitas;
import Modelo.Cita;
import Modelo.EstadoCita;
import Modelo.Medico;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALARCON
 */
public class AgendaMedicoPanel extends javax.swing.JPanel {

    private MedicoPanel medicoPanel; // Referencia al panel contenedor
    private Medico medico;
    private GestionCitas gestionCitas;
    private DefaultTableModel tableModel;
    private ArrayList<Cita> citasDelMedico;

    /**
     * Creates new form AgendaMedico
     */
    public AgendaMedicoPanel() {
        this(null, null, null);
    }

    public AgendaMedicoPanel(MedicoPanel medicoPanel, Medico medico, GestionCitas gestionCitas) {
        this.medicoPanel = medicoPanel;
        this.medico = medico;
        this.gestionCitas = gestionCitas;
        initComponents();

        String[] columnas = {"Hora", "Paciente", "Modalidad", "Estado"};
        tableModel = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaAgenda.setModel(tableModel);

        tablaAgenda.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = tablaAgenda.getSelectedRow();
                boolean isReady = selectedRow != -1 && citasDelMedico.get(selectedRow).getEstado() == EstadoCita.EN_SALA;
                iniciarConsultaButton.setEnabled(isReady);
            }
        });
    }

    public void refrescarAgenda() {
        cargarAgenda();
    }

    private void cargarAgenda() {
        String fecha = fechaField.getText();
        if (fecha == null || fecha.trim().isEmpty()) {
            tableModel.setRowCount(0);
            return;
        }

        ArrayList<Cita> todasLasCitasDelDia = gestionCitas.buscarCitaPorFecha(fecha.trim());
        citasDelMedico = new ArrayList<>();
        for (Cita cita : todasLasCitasDelDia) {
            if (cita.getMedico().equals(medico) && cita.getEstado() != EstadoCita.CANCELADA) {
                citasDelMedico.add(cita);
            }
        }

        tableModel.setRowCount(0);
        for (Cita cita : citasDelMedico) {
            Object[] row = {
                cita.getFechaHora().substring(11),
                cita.getPaciente(),
                cita.getModalidad(),
                cita.getEstado()
            };
            tableModel.addRow(row);
        }
        iniciarConsultaButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fechaField = new javax.swing.JTextField();
        verAgendaButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAgenda = new javax.swing.JTable();
        iniciarConsultaButton = new javax.swing.JButton();

        jLabel1.setText("Agenda del dia");

        jLabel2.setText("Ver agenda para la fecha (yyyy/mm/dd)");

        verAgendaButton.setText("Ver Agenda");
        verAgendaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verAgendaButtonActionPerformed(evt);
            }
        });

        tablaAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaAgenda);

        iniciarConsultaButton.setText("Iniciar Consulta");
        iniciarConsultaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarConsultaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechaField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(verAgendaButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(iniciarConsultaButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fechaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verAgendaButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iniciarConsultaButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void verAgendaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verAgendaButtonActionPerformed
        cargarAgenda();
    }//GEN-LAST:event_verAgendaButtonActionPerformed

    private void iniciarConsultaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarConsultaButtonActionPerformed
        int selectedRow = tablaAgenda.getSelectedRow();
        if (selectedRow != -1) {
            medicoPanel.iniciarConsulta(citasDelMedico.get(selectedRow));
        }
    }//GEN-LAST:event_iniciarConsultaButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fechaField;
    private javax.swing.JButton iniciarConsultaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAgenda;
    private javax.swing.JButton verAgendaButton;
    // End of variables declaration//GEN-END:variables
}
