/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Gestion.GestionCitas;
import Gestion.GestionConsultorios;
import Gestion.GestionEmpleados;
import Gestion.GestionPacientes;
import Modelo.Cita;
import Modelo.Consultorio;
import Modelo.Empleado;
import Modelo.EstadoCita;
import Modelo.Medico;
import Modelo.ModalidadCita;
import Modelo.Paciente;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author erick
 */
public class CitasGestionPanel extends javax.swing.JPanel {

    private GestionCitas gestionCitas;
    private GestionPacientes gestionPacientes;
    private GestionEmpleados gestionEmpleados;
    private GestionConsultorios gestionConsultorios;

    private DefaultTableModel tableModel;
    private ArrayList<Cita> citasMostradas;

    /**
     * Creates new form CitasGestionPanel
     */
    public CitasGestionPanel() {
        initComponents();
    }

    public CitasGestionPanel(GestionCitas gestionCitas, GestionPacientes gestionPacientes, GestionEmpleados gestionEmpleados, GestionConsultorios gestionConsultorios) {
        this.gestionCitas = gestionCitas;
        this.gestionPacientes = gestionPacientes;
        this.gestionEmpleados = gestionEmpleados;
        this.gestionConsultorios = gestionConsultorios;
        this.citasMostradas = new ArrayList<>();
        initComponents();

        ArrayList<String> especialidades = getEspecialidades();
        especialidades.add(0, "Todas");
        
        especialidadFilterComboBox.setModel(new DefaultComboBoxModel<>(especialidades.toArray(new String[0])));
        especialidadFilterComboBox.setSelectedIndex(0);
        pacienteComboBox.setModel(new DefaultComboBoxModel<>(gestionPacientes.getPacientes().toArray(new Paciente[0])));
        medicoComboBox.setModel(new DefaultComboBoxModel<>(getMedicos().toArray(new Medico[0])));
        consultorioComboBox.setModel(new DefaultComboBoxModel<>(gestionConsultorios.getConsultorios().toArray(new Consultorio[0])));
        modalidadComboBox.setModel(new DefaultComboBoxModel<>(ModalidadCita.values()));

        String[] columnas = {"Fecha/Hora", "Paciente", "Médico", "Especialidad", "Consultorio", "Estado"};
        tableModel = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaCitas.setModel(tableModel);

        tablaCitas.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && tablaCitas.getSelectedRow() != -1) {
                cargarDatosDeCitaSeleccionada();
            }
        });

        buscarCitas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modificarButton = new javax.swing.JButton();
        crearButton = new javax.swing.JButton();
        limpiarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCitas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        especialidadFilterComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        buscarButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pacienteComboBox = new javax.swing.JComboBox<>();
        medicoComboBox = new javax.swing.JComboBox<>();
        consultorioComboBox = new javax.swing.JComboBox<>();
        fechaHoraField = new javax.swing.JTextField();
        modalidadComboBox = new javax.swing.JComboBox<>();
        fechaFilterField = new javax.swing.JTextField();

        modificarButton.setText("Modificar Cita");
        modificarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarButtonActionPerformed(evt);
            }
        });

        crearButton.setText("Crear Cita");
        crearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearButtonActionPerformed(evt);
            }
        });

        limpiarButton.setText("Limpiar Formulario");
        limpiarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarButtonActionPerformed(evt);
            }
        });

        eliminarButton.setText("Cancelar Cita");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        tablaCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "DNI", "Nombres"
            }
        ));
        jScrollPane2.setViewportView(tablaCitas);

        jLabel1.setText("Buscar Citas");

        jLabel2.setText("Especialidad:");

        jLabel3.setText("Fecha (yyyy/mm/dd):");

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Gestionar Cita");

        jLabel5.setText("Paciente:");

        jLabel6.setText("Medico:");

        jLabel7.setText("Consultorio:");

        jLabel8.setText("Fecha y Hora (yyyy/mm/dd hh:mm):");

        jLabel9.setText("Modalidad:");

        fechaHoraField.setText("yyyy/mm/dd hh:mm");

        fechaFilterField.setText("yyyy/mm/dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pacienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(medicoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(consultorioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(especialidadFilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fechaFilterField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buscarButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fechaHoraField)
                            .addComponent(modalidadComboBox, 0, 330, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(crearButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limpiarButton)
                .addGap(259, 259, 259))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(especialidadFilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(buscarButton)
                    .addComponent(fechaFilterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pacienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(medicoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(consultorioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fechaHoraField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(modalidadComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearButton)
                    .addComponent(modificarButton)
                    .addComponent(eliminarButton)
                    .addComponent(limpiarButton))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modificarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarButtonActionPerformed
        int selectedRow = tablaCitas.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una cita para modificar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Cita citaOriginal = citasMostradas.get(selectedRow);
        Paciente nuevoPaciente = (Paciente) pacienteComboBox.getSelectedItem();
        Medico nuevoMedico = (Medico) medicoComboBox.getSelectedItem();
        Consultorio nuevoConsultorio = (Consultorio) consultorioComboBox.getSelectedItem();
        String nuevaFechaHora = fechaHoraField.getText();
        ModalidadCita nuevaModalidad = (ModalidadCita) modalidadComboBox.getSelectedItem();

        if (citaOriginal.getEstado() == EstadoCita.ATENDIDA || citaOriginal.getEstado() == EstadoCita.CANCELADA) {
            JOptionPane.showMessageDialog(this, "No se puede modificar una cita atendida o cancelada.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (gestionCitas.modificarCita(citaOriginal, nuevaFechaHora, nuevoMedico, nuevoConsultorio)) {
            citaOriginal.setPaciente(nuevoPaciente);
            citaOriginal.setModalidad(nuevaModalidad);
            JOptionPane.showMessageDialog(this, "Cita modificada exitosamente.");
            buscarCitas();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo modificar la cita. Verifique la disponibilidad.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_modificarButtonActionPerformed

    private void crearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearButtonActionPerformed
        Paciente paciente = (Paciente) pacienteComboBox.getSelectedItem();
        Medico medico = (Medico) medicoComboBox.getSelectedItem();
        Consultorio consultorio = (Consultorio) consultorioComboBox.getSelectedItem();
        String fechaHora = fechaHoraField.getText();
        ModalidadCita modalidad = (ModalidadCita) modalidadComboBox.getSelectedItem();

        if (paciente == null || medico == null || consultorio == null || fechaHora.isEmpty() || fechaHora.equals("yyyy/mm/dd hh:mm")) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (gestionCitas.crearCita(fechaHora, medico, consultorio, paciente, modalidad)) {
            JOptionPane.showMessageDialog(this, "Cita creada exitosamente.");
            buscarCitas();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo crear la cita. Verifique la disponibilidad.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_crearButtonActionPerformed

    private void limpiarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarButtonActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_limpiarButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        int selectedRow = tablaCitas.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una cita para cancelar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Cita citaSeleccionada = citasMostradas.get(selectedRow);
        int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea cancelar esta cita?", "Confirmar Cancelación", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            if (gestionCitas.cancelarCita(citaSeleccionada)) {
                JOptionPane.showMessageDialog(this, "Cita cancelada.");
                buscarCitas();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo cancelar la cita.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        buscarCitas();
    }//GEN-LAST:event_buscarButtonActionPerformed

    private ArrayList<Medico> getMedicos() {
        ArrayList<Medico> medicos = new ArrayList<>();
        for (Empleado empleado : gestionEmpleados.getEmpleados()) {
            if (empleado instanceof Medico) {
                medicos.add((Medico) empleado);
            }
        }
        return medicos;
    }

    private ArrayList<String> getEspecialidades() {
        ArrayList<String> especialidades = new ArrayList<>();
        for (Medico med : getMedicos()) {
            if (!especialidades.contains(med.getEspecialidad())) {
                especialidades.add(med.getEspecialidad());
            }
        }
        return especialidades;
    }

    private void buscarCitas() {
        String especialidad = (String) especialidadFilterComboBox.getSelectedItem();
        String fecha = fechaFilterField.getText();

        ArrayList<Cita> resultado;

        if (especialidad != null && !especialidad.equals("Todas")) {
            resultado = gestionCitas.buscarCitaPorEspecialidad(especialidad);
        } else {
            resultado = gestionCitas.getCitas();
        }

        if (fecha != null && !fecha.trim().isEmpty() && !fecha.equals("yyyy/mm/dd")) {
            ArrayList<Cita> citasPorFecha = new ArrayList<>();
            for (Cita c : resultado) {
                if (c.getFechaHora().startsWith(fecha.trim())) {
                    citasPorFecha.add(c);
                }
            }
            resultado = citasPorFecha;
        }

        actualizarTabla(resultado);
    }

    private void cargarDatosDeCitaSeleccionada() {
        int selectedRow = tablaCitas.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }

        Cita citaSeleccionada = citasMostradas.get(selectedRow);
        pacienteComboBox.setSelectedItem(citaSeleccionada.getPaciente());
        medicoComboBox.setSelectedItem(citaSeleccionada.getMedico());
        consultorioComboBox.setSelectedItem(citaSeleccionada.getConsultorio());
        fechaHoraField.setText(citaSeleccionada.getFechaHora());
        modalidadComboBox.setSelectedItem(citaSeleccionada.getModalidad());
    }

    private void actualizarTabla(ArrayList<Cita> citas) {
        tableModel.setRowCount(0);
        this.citasMostradas = citas;
        for (Cita cita : citas) {
            Object[] row = {
                cita.getFechaHora(),
                cita.getPaciente(),
                cita.getMedico(),
                cita.getMedico().getEspecialidad(),
                cita.getConsultorio().getCodigo(),
                cita.getEstado()
            };
            tableModel.addRow(row);
        }
    }

    private void limpiarCampos() {
        pacienteComboBox.setSelectedIndex(-1);
        medicoComboBox.setSelectedIndex(-1);
        consultorioComboBox.setSelectedIndex(-1);
        fechaHoraField.setText("yyyy/mm/dd hh:mm");
        modalidadComboBox.setSelectedIndex(0);
        tablaCitas.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButton;
    private javax.swing.JComboBox<Consultorio> consultorioComboBox;
    private javax.swing.JButton crearButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JComboBox<String> especialidadFilterComboBox;
    private javax.swing.JTextField fechaFilterField;
    private javax.swing.JTextField fechaHoraField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton limpiarButton;
    private javax.swing.JComboBox<Medico> medicoComboBox;
    private javax.swing.JComboBox<ModalidadCita> modalidadComboBox;
    private javax.swing.JButton modificarButton;
    private javax.swing.JComboBox<Paciente> pacienteComboBox;
    private javax.swing.JTable tablaCitas;
    // End of variables declaration//GEN-END:variables
}
