/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Gestion.GestionConsultorios;
import Modelo.Consultorio;
import Modelo.EstadoConsultorio;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author erick
 */
public class ConsultoriosGestionPanel extends javax.swing.JPanel {

    private GestionConsultorios gestionConsultorios;
    private DefaultTableModel tableModel;

    /**
     * Creates new form ConsultoriosGestionPanel
     */
    public ConsultoriosGestionPanel() {
        this(null);
    }

    public ConsultoriosGestionPanel(GestionConsultorios gestionConsultorios) {
        this.gestionConsultorios = gestionConsultorios;
        initComponents();

        String[] columnas = {"Código", "Especialidad", "Estado"};
        tableModel = new DefaultTableModel(columnas, 0);
        tablaConsultorios.setModel(tableModel);

        cargarComboBox();

        actualizarTabla();

        tablaConsultorios.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && tablaConsultorios.getSelectedRow() != -1) {
                cargarDatosDeFilaSeleccionada();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        limpiarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        modificarButton = new javax.swing.JButton();
        crearButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        codigoField = new javax.swing.JTextField();
        estadoComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConsultorios = new javax.swing.JTable();
        limpiarButton1 = new javax.swing.JButton();
        eliminarButton1 = new javax.swing.JButton();
        modificarButton1 = new javax.swing.JButton();
        crearButton1 = new javax.swing.JButton();
        especialidadField = new javax.swing.JTextField();

        limpiarButton.setText("Limpiar");
        limpiarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarButtonActionPerformed(evt);
            }
        });

        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        modificarButton.setText("Modificar");
        modificarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarButtonActionPerformed(evt);
            }
        });

        crearButton.setText("Crear");
        crearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo:");

        jLabel2.setText("Especialidad:");

        jLabel3.setText("Estado:");

        tablaConsultorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaConsultorios);

        limpiarButton1.setText("Limpiar");
        limpiarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarButton1ActionPerformed(evt);
            }
        });

        eliminarButton1.setText("Eliminar");
        eliminarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButton1ActionPerformed(evt);
            }
        });

        modificarButton1.setText("Modificar");
        modificarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarButton1ActionPerformed(evt);
            }
        });

        crearButton1.setText("Crear");
        crearButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearButton1ActionPerformed(evt);
            }
        });

        especialidadField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialidadFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(205, 205, 205)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoField, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                            .addComponent(estadoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(especialidadField))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(crearButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificarButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limpiarButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codigoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(especialidadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(estadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearButton1)
                    .addComponent(modificarButton1)
                    .addComponent(eliminarButton1)
                    .addComponent(limpiarButton1))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarButtonActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_limpiarButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        int selectedRow = tablaConsultorios.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un consultorio para eliminar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int codigo = (int) tableModel.getValueAt(selectedRow, 0);
        int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea eliminar el consultorio " + codigo + "?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            if (gestionConsultorios.eliminarConsultorio(codigo)) {
                JOptionPane.showMessageDialog(this, "Consultorio eliminado.");
                actualizarTabla();
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar el consultorio.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void modificarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarButtonActionPerformed
        int selectedRow = tablaConsultorios.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un consultorio para modificar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int codigoOriginal = (int) tableModel.getValueAt(selectedRow, 0);
            int codigoNuevo = Integer.parseInt(codigoField.getText());
            String especialidad = especialidadField.getText();
            EstadoConsultorio estado = (EstadoConsultorio) estadoComboBox.getSelectedItem();

            if (gestionConsultorios.modificarConsultorio(codigoOriginal, especialidad, null, null, estado, codigoNuevo)) {
                JOptionPane.showMessageDialog(this, "Consultorio modificado con éxito.");
                actualizarTabla();
            } else {
                JOptionPane.showMessageDialog(this, "Error al modificar. El nuevo código podría ya existir.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El código debe ser un número válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_modificarButtonActionPerformed

    private void crearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearButtonActionPerformed
        try {
            int codigo = Integer.parseInt(codigoField.getText());
            String especialidad = especialidadField.getText();
            EstadoConsultorio estado = (EstadoConsultorio) estadoComboBox.getSelectedItem();

            if (especialidad.isEmpty()) {
                JOptionPane.showMessageDialog(this, "La especialidad es obligatoria.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Consultorio nuevoConsultorio = new Consultorio(codigo, especialidad, estado);
            if (gestionConsultorios.crearConsultorio(nuevoConsultorio)) {
                JOptionPane.showMessageDialog(this, "Consultorio creado exitosamente.");
                actualizarTabla();
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo crear el consultorio. El código ya podría existir.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El código debe ser un número válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_crearButtonActionPerformed

    private void limpiarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarButton1ActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_limpiarButton1ActionPerformed

    private void eliminarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButton1ActionPerformed
        int selectedRow = tablaConsultorios.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un consultorio para eliminar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int codigo = (int) tableModel.getValueAt(selectedRow, 0);
        int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea eliminar el consultorio " + codigo + "?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            if (gestionConsultorios.eliminarConsultorio(codigo)) {
                JOptionPane.showMessageDialog(this, "Consultorio eliminado.");
                actualizarTabla();
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar el consultorio.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_eliminarButton1ActionPerformed

    private void modificarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarButton1ActionPerformed
        int selectedRow = tablaConsultorios.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un consultorio para modificar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int codigoOriginal = (int) tableModel.getValueAt(selectedRow, 0);
            int codigoNuevo = Integer.parseInt(codigoField.getText());
            String especialidad = especialidadField.getText();
            EstadoConsultorio estado = (EstadoConsultorio) estadoComboBox.getSelectedItem();

            if (gestionConsultorios.modificarConsultorio(codigoOriginal, especialidad, null, null, estado, codigoNuevo)) {
                JOptionPane.showMessageDialog(this, "Consultorio modificado con éxito.");
                actualizarTabla();
            } else {
                JOptionPane.showMessageDialog(this, "Error al modificar. El nuevo código podría ya existir.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El código debe ser un número válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_modificarButton1ActionPerformed

    private void crearButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearButton1ActionPerformed
        try {
            int codigo = Integer.parseInt(codigoField.getText());
            String especialidad = especialidadField.getText();
            EstadoConsultorio estado = (EstadoConsultorio) estadoComboBox.getSelectedItem();

            if (especialidad.isEmpty()) {
                JOptionPane.showMessageDialog(this, "La especialidad es obligatoria.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Consultorio nuevoConsultorio = new Consultorio(codigo, especialidad, estado);
            if (gestionConsultorios.crearConsultorio(nuevoConsultorio)) {
                JOptionPane.showMessageDialog(this, "Consultorio creado exitosamente.");
                actualizarTabla();
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo crear el consultorio. El código ya podría existir.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El código debe ser un número válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_crearButton1ActionPerformed

    private void especialidadFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidadFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especialidadFieldActionPerformed

    private void cargarDatosDeFilaSeleccionada() {
        int selectedRow = tablaConsultorios.getSelectedRow();
        codigoField.setText(tableModel.getValueAt(selectedRow, 0).toString());
        especialidadField.setText(tableModel.getValueAt(selectedRow, 1).toString());
        estadoComboBox.setSelectedItem(tableModel.getValueAt(selectedRow, 2));
    }

    private void cargarComboBox() {
        estadoComboBox.setModel(new DefaultComboBoxModel<>(EstadoConsultorio.values()));
    }

    private void actualizarTabla() {
        tableModel.setRowCount(0);
        ArrayList<Consultorio> lista = gestionConsultorios.getConsultorios();
        for (Consultorio consultorio : lista) {
            Object[] row = {
                consultorio.getCodigo(),
                consultorio.getEspecialidad(),
                consultorio.getEstado()
            };
            tableModel.addRow(row);
        }
    }

    private void limpiarCampos() {
        codigoField.setText("");
        especialidadField.setText("");
        estadoComboBox.setSelectedIndex(0);
        tablaConsultorios.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigoField;
    private javax.swing.JButton crearButton;
    private javax.swing.JButton crearButton1;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JButton eliminarButton1;
    private javax.swing.JTextField especialidadField;
    private javax.swing.JComboBox<EstadoConsultorio> estadoComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiarButton;
    private javax.swing.JButton limpiarButton1;
    private javax.swing.JButton modificarButton;
    private javax.swing.JButton modificarButton1;
    private javax.swing.JTable tablaConsultorios;
    // End of variables declaration//GEN-END:variables

}
