/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Gestion.GestionEmpleados;
import Modelo.Administrador;
import Modelo.Cajero;
import Modelo.Empleado;
import Modelo.Enfermero;
import Modelo.Medico;
import Modelo.Recepcionista;
import Modelo.RolEmpleado;
import static Modelo.RolEmpleado.ADMINISTRADOR;
import static Modelo.RolEmpleado.CAJERO;
import static Modelo.RolEmpleado.ENFERMERO;
import static Modelo.RolEmpleado.MEDICO;
import static Modelo.RolEmpleado.RECEPCIONISTA;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author erick
 */
public class EmpleadosGestionPanel extends javax.swing.JPanel {

    private final GestionEmpleados gestionEmpleados;
    private DefaultTableModel tableModel;

    /**
     * Creates new form EmpleadosGestionPanel
     */
    public EmpleadosGestionPanel() {
        this(null);
    }

    public EmpleadosGestionPanel(GestionEmpleados gestionEmpleados) {
        this.gestionEmpleados = gestionEmpleados;
        initComponents();

        String[] columnas = {"DNI", "Nombres", "Apellidos", "Rol", "Especialidad"};
        tableModel = new DefaultTableModel(columnas, 0);
        tablaEmpleados.setModel(tableModel);

        cargarComboBox();

        actualizarTabla();

        rolComboBox.addActionListener(e -> {
            boolean esMedico = rolComboBox.getSelectedItem() == RolEmpleado.MEDICO;
            especialidadField.setEnabled(esMedico);
            if (!esMedico) {
                especialidadField.setText("");
            }
        });
        rolComboBox.setSelectedIndex(0);

        tablaEmpleados.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && tablaEmpleados.getSelectedRow() != -1) {
                cargarDatosDeFilaSeleccionada();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dniField = new javax.swing.JTextField();
        nombresField = new javax.swing.JTextField();
        apellidosField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        rolComboBox = new javax.swing.JComboBox<>();
        especialidadField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        modificarButton = new javax.swing.JButton();
        crearButton = new javax.swing.JButton();
        limpiarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setPreferredSize(new java.awt.Dimension(600, 600));

        jLabel1.setText("DNI:");

        jLabel2.setText("Nombres:");

        jLabel3.setText("Apellidos");

        jLabel4.setText("Contrasena:");

        jLabel5.setText("Rol:");

        jLabel6.setText("Especialidad (si es Medico):");

        rolComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolComboBoxActionPerformed(evt);
            }
        });

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombres", "Apellidos", "Rol", "Especialidad"
            }
        ));
        jScrollPane2.setViewportView(tablaEmpleados);

        modificarButton.setText("Modificar");
        modificarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarButtonActionPerformed(evt);
            }
        });

        crearButton.setText("Crear");
        crearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearButtonActionPerformed(evt);
            }
        });

        limpiarButton.setText("Limpiar");
        limpiarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarButtonActionPerformed(evt);
            }
        });

        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(especialidadField)
                    .addComponent(passwordField)
                    .addComponent(apellidosField)
                    .addComponent(rolComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombresField)
                    .addComponent(dniField))
                .addContainerGap())
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(crearButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limpiarButton)
                .addContainerGap(239, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dniField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombresField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(apellidosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rolComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(especialidadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearButton)
                    .addComponent(modificarButton)
                    .addComponent(eliminarButton)
                    .addComponent(limpiarButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rolComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rolComboBoxActionPerformed

    private void crearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearButtonActionPerformed
        try {
            int dni = Integer.parseInt(dniField.getText());
            String nombres = nombresField.getText();
            String apellidos = apellidosField.getText();
            String password = new String(passwordField.getPassword());
            RolEmpleado rol = (RolEmpleado) rolComboBox.getSelectedItem();

            if (nombres.isEmpty() || apellidos.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Empleado nuevoEmpleado = null;
            switch (rol) {
                case MEDICO:
                    String especialidad = especialidadField.getText();
                    if (especialidad.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "La especialidad es obligatoria para los médicos.", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    nuevoEmpleado = new Medico(dni, nombres, apellidos, password, especialidad);
                    break;
                case ADMINISTRADOR:
                    nuevoEmpleado = new Administrador(dni, nombres, apellidos, password);
                    break;
                case RECEPCIONISTA:
                    nuevoEmpleado = new Recepcionista(dni, nombres, apellidos, password);
                    break;
                case CAJERO:
                    nuevoEmpleado = new Cajero(dni, nombres, apellidos, password);
                    break;
                case ENFERMERO:
                    nuevoEmpleado = new Enfermero(dni, nombres, apellidos, password);
                    break;
            }

            if (nuevoEmpleado != null && gestionEmpleados.crearEmpleado(nuevoEmpleado)) {
                JOptionPane.showMessageDialog(this, "Empleado creado exitosamente.");
                actualizarTabla();
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo crear el empleado. El DNI ya podría existir.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El DNI debe ser un número válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_crearButtonActionPerformed

    private void modificarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarButtonActionPerformed
        int selectedRow = tablaEmpleados.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un empleado para modificar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int dniOriginal = (int) tableModel.getValueAt(selectedRow, 0);
            int dniNuevo = Integer.parseInt(dniField.getText());
            String nombres = nombresField.getText();
            String apellidos = apellidosField.getText();
            String password = new String(passwordField.getPassword()); // Puede estar vacío si no se quiere cambiar
            RolEmpleado rol = (RolEmpleado) rolComboBox.getSelectedItem();

            gestionEmpleados.eliminarEmpleado(dniOriginal);

            Empleado empleadoModificado = null;
            switch (rol) {
                case MEDICO:
                    empleadoModificado = new Medico(dniNuevo, nombres, apellidos, password, especialidadField.getText());
                    break;
                default:
                    empleadoModificado = new Administrador(dniNuevo, nombres, apellidos, password); // Simplificación
            }

            if (gestionEmpleados.crearEmpleado(empleadoModificado)) {
                JOptionPane.showMessageDialog(this, "Empleado modificado con éxito.");
                actualizarTabla();
            } else {
                JOptionPane.showMessageDialog(this, "Error al modificar. El nuevo DNI podría existir ya.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El DNI debe ser un número válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_modificarButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        int selectedRow = tablaEmpleados.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un empleado para eliminar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int dni = (int) tableModel.getValueAt(selectedRow, 0);
        int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea eliminar al empleado con DNI " + dni + "?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            if (gestionEmpleados.eliminarEmpleado(dni)) {
                JOptionPane.showMessageDialog(this, "Empleado eliminado.");
                actualizarTabla();
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar el empleado.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void limpiarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarButtonActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_limpiarButtonActionPerformed

    private void actualizarTabla() {
        tableModel.setRowCount(0); // Limpiar tabla
        ArrayList<Empleado> lista = gestionEmpleados.getEmpleados();
        for (Empleado emp : lista) {
            String especialidad = "";
            if (emp instanceof Medico) {
                especialidad = ((Medico) emp).getEspecialidad();
            }
            Object[] row = {
                emp.getDNI(),
                emp.getNombres(),
                emp.getApellidos(),
                emp.getRolEmpleado(),
                especialidad
            };
            tableModel.addRow(row);
        }
    }

    private void cargarDatosDeFilaSeleccionada() {
        int selectedRow = tablaEmpleados.getSelectedRow();
        dniField.setText(tableModel.getValueAt(selectedRow, 0).toString());
        nombresField.setText(tableModel.getValueAt(selectedRow, 1).toString());
        apellidosField.setText(tableModel.getValueAt(selectedRow, 2).toString());
        rolComboBox.setSelectedItem(tableModel.getValueAt(selectedRow, 3));
        especialidadField.setText(tableModel.getValueAt(selectedRow, 4).toString());
        passwordField.setText("");
    }

    private void limpiarCampos() {
        dniField.setText("");
        nombresField.setText("");
        apellidosField.setText("");
        passwordField.setText("");
        rolComboBox.setSelectedIndex(0);
        especialidadField.setText("");
        tablaEmpleados.clearSelection();
    }

    private void cargarComboBox() {
        rolComboBox.setModel(new DefaultComboBoxModel<>(RolEmpleado.values()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosField;
    private javax.swing.JButton crearButton;
    private javax.swing.JTextField dniField;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JTextField especialidadField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton limpiarButton;
    private javax.swing.JButton modificarButton;
    private javax.swing.JTextField nombresField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JComboBox<RolEmpleado> rolComboBox;
    private javax.swing.JTable tablaEmpleados;
    // End of variables declaration//GEN-END:variables

}
