/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Gestion.GestionHistoriasClinicas;
import Gestion.GestionPacientes;
import Modelo.Consulta;
import Modelo.HistoriaClinica;
import Modelo.Paciente;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ALARCON
 */
public class HistoriaClinicaPanel extends javax.swing.JPanel {

    private GestionPacientes gestionPacientes;
    private GestionHistoriasClinicas gestionHistorias;
    private DefaultListModel<Consulta> lista;

    /**
     * Creates new form HistoriaClinicaPanel
     */
    public HistoriaClinicaPanel() {
        initComponents();
    }

    public HistoriaClinicaPanel(GestionPacientes gestionPacientes, GestionHistoriasClinicas gestionHistorias) {
        this.gestionPacientes = gestionPacientes;
        this.gestionHistorias = gestionHistorias;
        initComponents();

        lista = new DefaultListModel<>();
        listaConsultas.setModel(lista);

        detalleConsultaArea.setEditable(false);

        listaConsultas.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                mostrarDetalleConsulta(listaConsultas.getSelectedValue());
            }
        });
    }

    private void buscarHistoria() {
        try {
            int dni = Integer.parseInt(dniField.getText());
            Paciente paciente = gestionPacientes.buscarPorDNI(dni);

            lista.clear();
            detalleConsultaArea.setText("");

            if (paciente == null) {
                estadoPaciente.setText("Paciente no encontrado.");
                JOptionPane.showMessageDialog(this, "No se encontró ningún paciente con ese DNI.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            estadoPaciente.setText("Mostrando historia de: " + paciente.getNombres() + " " + paciente.getApellidos());
            HistoriaClinica historia = gestionHistorias.getHistoriaClinica(paciente);
            ArrayList<Consulta> consultas = historia.getConsultas();

            if (consultas.isEmpty()) {
                lista.addElement(null);
            } else {
                for (Consulta consulta : consultas) {
                    lista.addElement(consulta);
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El DNI debe ser un número válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void mostrarDetalleConsulta(Consulta consulta) {
        if (consulta == null) {
            detalleConsultaArea.setText("No hay consultas registradas para este paciente.");
            return;
        }

        StringBuilder sb = new StringBuilder();
        sb.append("Fecha: ").append(consulta.getFecha()).append("\n");
        sb.append("Médico: ").append(consulta.getMedico().getNombres()).append(" ").append(consulta.getMedico().getApellidos()).append("\n");
        sb.append("-----------------------------------\n\n");
        sb.append("Motivo de Consulta:\n").append(consulta.getMotivo()).append("\n\n");
        sb.append("Antecedentes:\n").append(consulta.getAntecedentes()).append("\n\n");
        sb.append("Signos Vitales:\n").append(consulta.getSignosVitales()).append("\n\n");
        sb.append("Examen Físico:\n").append(consulta.getExamenFisico()).append("\n\n");
        sb.append("Diagnóstico:\n").append(consulta.getDiagnostico()).append("\n\n");
        sb.append("Plan de Tratamiento:\n").append(consulta.getPlan()).append("\n");

        detalleConsultaArea.setText(sb.toString());
        detalleConsultaArea.setCaretPosition(0); // Scroll al inicio
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dniField = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScroll = new javax.swing.JScrollPane();
        detalleConsultaArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        estadoPaciente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaConsultas = new javax.swing.JList<>();

        jLabel1.setText("Historia Clinica");

        jLabel2.setText("DNI del Paciente");

        buscarButton.setText("Buscar Paciente");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setMaximumSize(new java.awt.Dimension(400, 600));
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 509));

        jLabel4.setText("Detalles de la Consulta");

        detalleConsultaArea.setColumns(20);
        detalleConsultaArea.setRows(5);
        jScroll.setViewportView(detalleConsultaArea);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(jPanel4);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setMinimumSize(new java.awt.Dimension(300, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 509));

        estadoPaciente.setText("Detalle del Paciente");

        jScrollPane1.setViewportView(listaConsultas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(estadoPaciente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(estadoPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dniField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dniField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarButton))
                .addGap(18, 18, 18)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        buscarHistoria();
    }//GEN-LAST:event_buscarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButton;
    private javax.swing.JTextArea detalleConsultaArea;
    private javax.swing.JTextField dniField;
    private javax.swing.JLabel estadoPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScroll;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JList<Consulta> listaConsultas;
    // End of variables declaration//GEN-END:variables
}
