/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Gestion.GestionCitas;
import Gestion.GestionHistoriasClinicas;
import Gestion.GestionPacientes;
import Modelo.Cita;
import Modelo.Medico;

/**
 *
 * @author ALARCON
 */
public class MedicoPanel extends javax.swing.JPanel {
    
    private MainFrame mainFrame;
    private Medico medico;
    private GestionCitas gestionCitas;
    private GestionHistoriasClinicas gestionHistorias;
    private GestionPacientes gestionPacientes;
    
    private AgendaMedicoPanel agendaPanel;
    private AtencionPanel atencionPanel;
    private HistoriaClinicaPanel historiaPanel;
    
    /**
     * Creates new form MedicoPanel
     */
    public MedicoPanel() {
        this(null, null, null, null, null);
    }
    
    public MedicoPanel(MainFrame mainFrame, Medico medico, GestionCitas gestionCitas, GestionHistoriasClinicas gestionHistorias, GestionPacientes gestionPacientes) {
        this.mainFrame = mainFrame;
        this.medico = medico;
        this.gestionCitas = gestionCitas;
        this.gestionHistorias = gestionHistorias;
        this.gestionPacientes = gestionPacientes;
        initComponents();
        
        jLabel1.setText("Bienvenido, Dr. " + medico.getNombres() + " " + medico.getApellidos());
        
        agendaPanel = new AgendaMedicoPanel(this, medico, gestionCitas);
        atencionPanel = new AtencionPanel(gestionHistorias, this);
        historiaPanel = new HistoriaClinicaPanel(gestionPacientes, gestionHistorias);
        tabbedPane.addTab("Agenda del Día", agendaPanel);
        tabbedPane.addTab("Atención Clínica", atencionPanel);
        tabbedPane.addTab("Historia Clínica", historiaPanel);
    }
    
    public void iniciarConsulta(Cita cita) {
        atencionPanel.iniciarAtencion(cita, this.medico);
        tabbedPane.setSelectedIndex(1);
        tabbedPane.setEnabledAt(0, false);
        tabbedPane.setEnabledAt(1, true);
    }
    
    public void mostrarAgenda() {
        agendaPanel.refrescarAgenda();
        tabbedPane.setSelectedIndex(0);
        tabbedPane.setEnabledAt(0, true);
        tabbedPane.setEnabledAt(1, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tabbedPane = new javax.swing.JTabbedPane();
        logoutButton = new java.awt.Button();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Bienvenido");

        logoutButton.setLabel("Cerrar Sesion");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        mainFrame.mostrarLoginPanel();
    }//GEN-LAST:event_logoutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private java.awt.Button logoutButton;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
