/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Gestion.GestionCitas;
import Gestion.GestionConsultorios;
import Gestion.GestionEmpleados;
import Gestion.GestionFacturacion;
import Modelo.Cita;
import Modelo.Consultorio;
import Modelo.Empleado;
import Modelo.Factura;
import Modelo.Medico;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author erick
 */
public class ReportesPanel extends javax.swing.JPanel {

    private GestionConsultorios gestionConsultorios;
    private GestionCitas gestionCitas;
    private GestionFacturacion gestionFacturacion;
    private GestionEmpleados gestionEmpleados;

    /**
     * Creates new form ReportesPanel
     */
    public ReportesPanel() {
        this(null, null, null, null);
    }

    public ReportesPanel(GestionConsultorios gestionConsultorios, GestionCitas gestionCitas, GestionFacturacion gestionFacturacion, GestionEmpleados gestionEmpleados) {
        this.gestionConsultorios = gestionConsultorios;
        this.gestionCitas = gestionCitas;
        this.gestionFacturacion = gestionFacturacion;
        this.gestionEmpleados = gestionEmpleados;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        tabbedPane = new javax.swing.JTabbedPane();
        reporteOcupacionPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ocupacionFechaField = new javax.swing.JTextField();
        reporteOcupacionButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ocupacionArea = new javax.swing.JTextArea();
        reporteProduccionPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        inicioProduccionField = new javax.swing.JTextField();
        reporteProduccionButton = new javax.swing.JButton();
        finProduccionField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        produccionArea = new javax.swing.JTextArea();
        reporteIngresosPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        inicioIngresosField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        finIngresosField = new javax.swing.JTextField();
        reporteIngresosButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ingresosArea = new javax.swing.JTextArea();

        jMenuItem1.setText("jMenuItem1");

        tabbedPane.setToolTipText("Ocupación de Consultorios");
        tabbedPane.setName(""); // NOI18N

        reporteOcupacionPanel.setToolTipText("");

        jLabel1.setText("Fecha (yyyy/mm/dd):");

        ocupacionFechaField.setText("yyyy/mm/dd");
        ocupacionFechaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocupacionFechaFieldActionPerformed(evt);
            }
        });

        reporteOcupacionButton.setText("Generar Reporte de Ocupación");
        reporteOcupacionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteOcupacionButtonActionPerformed(evt);
            }
        });

        ocupacionArea.setColumns(20);
        ocupacionArea.setRows(5);
        jScrollPane1.setViewportView(ocupacionArea);

        javax.swing.GroupLayout reporteOcupacionPanelLayout = new javax.swing.GroupLayout(reporteOcupacionPanel);
        reporteOcupacionPanel.setLayout(reporteOcupacionPanelLayout);
        reporteOcupacionPanelLayout.setHorizontalGroup(
            reporteOcupacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporteOcupacionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reporteOcupacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(reporteOcupacionPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ocupacionFechaField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reporteOcupacionButton)
                        .addGap(0, 499, Short.MAX_VALUE)))
                .addContainerGap())
        );
        reporteOcupacionPanelLayout.setVerticalGroup(
            reporteOcupacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporteOcupacionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reporteOcupacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ocupacionFechaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reporteOcupacionButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane.addTab("Ocupación de Consultorios", reporteOcupacionPanel);

        jLabel2.setText("Fecha Inicio (yyyy/mm/dd):");

        inicioProduccionField.setText("yyyy/mm/dd");
        inicioProduccionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioProduccionFieldActionPerformed(evt);
            }
        });

        reporteProduccionButton.setText("Generar Reporte de Producción");
        reporteProduccionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteProduccionButtonActionPerformed(evt);
            }
        });

        finProduccionField.setText("yyyy/mm/dd");
        finProduccionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finProduccionFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha Fin (yyyy/mm/dd):");

        produccionArea.setColumns(20);
        produccionArea.setRows(5);
        jScrollPane2.setViewportView(produccionArea);

        javax.swing.GroupLayout reporteProduccionPanelLayout = new javax.swing.GroupLayout(reporteProduccionPanel);
        reporteProduccionPanel.setLayout(reporteProduccionPanelLayout);
        reporteProduccionPanelLayout.setHorizontalGroup(
            reporteProduccionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporteProduccionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reporteProduccionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reporteProduccionPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inicioProduccionField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finProduccionField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reporteProduccionButton)
                        .addGap(0, 191, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        reporteProduccionPanelLayout.setVerticalGroup(
            reporteProduccionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporteProduccionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reporteProduccionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inicioProduccionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(finProduccionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reporteProduccionButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        tabbedPane.addTab("Producción por Médico", reporteProduccionPanel);

        jLabel4.setText("Fecha Inicio (yyyy/mm/dd):");

        inicioIngresosField.setText("yyyy/mm/dd");
        inicioIngresosField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioIngresosFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Fecha Fin (yyyy/mm/dd):");

        finIngresosField.setText("yyyy/mm/dd");
        finIngresosField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finIngresosFieldActionPerformed(evt);
            }
        });

        reporteIngresosButton.setText("Generar Reporte de Ingresos");
        reporteIngresosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteIngresosButtonActionPerformed(evt);
            }
        });

        ingresosArea.setColumns(20);
        ingresosArea.setRows(5);
        jScrollPane3.setViewportView(ingresosArea);

        javax.swing.GroupLayout reporteIngresosPanelLayout = new javax.swing.GroupLayout(reporteIngresosPanel);
        reporteIngresosPanel.setLayout(reporteIngresosPanelLayout);
        reporteIngresosPanelLayout.setHorizontalGroup(
            reporteIngresosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporteIngresosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reporteIngresosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reporteIngresosPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inicioIngresosField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finIngresosField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reporteIngresosButton)
                        .addGap(0, 205, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        reporteIngresosPanelLayout.setVerticalGroup(
            reporteIngresosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporteIngresosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reporteIngresosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inicioIngresosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(finIngresosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reporteIngresosButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        tabbedPane.addTab("Ingresos por Fechas", reporteIngresosPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane)
                .addContainerGap())
        );

        tabbedPane.getAccessibleContext().setAccessibleName("");
        tabbedPane.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void ocupacionFechaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocupacionFechaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ocupacionFechaFieldActionPerformed

    private void inicioProduccionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioProduccionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inicioProduccionFieldActionPerformed

    private void finProduccionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finProduccionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finProduccionFieldActionPerformed

    private void reporteProduccionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteProduccionButtonActionPerformed
        String fechaInicio = inicioProduccionField.getText();
        String fechaFin = finProduccionField.getText();

        StringBuilder sb = new StringBuilder("--- Reporte de Producción por Médico ---\n");
        if (!fechaInicio.isEmpty() && !fechaFin.isEmpty()) {
            sb.append("Periodo: ").append(fechaInicio).append(" al ").append(fechaFin).append("\n\n");
        }

        for (Empleado empleado : gestionEmpleados.getEmpleados()) {
            if (empleado instanceof Medico) {
                Medico medico = (Medico) empleado;
                int consultas = 0;
                int facturasEmitidas = 0;

                for (Factura factura : gestionFacturacion.getFacturas()) {
                    boolean enRango = (fechaInicio.isEmpty() || factura.getFecha().compareTo(fechaInicio) >= 0)
                            && (fechaFin.isEmpty() || factura.getFecha().compareTo(fechaFin) <= 0);

                    if (factura.getCita().getMedico().equals(medico) && enRango) {
                        consultas++; // Cada factura corresponde a una consulta
                        facturasEmitidas++;
                    }
                }
                sb.append("Dr. ").append(medico.getNombres()).append(" ").append(medico.getApellidos()).append(" (").append(medico.getEspecialidad()).append("):\n");
                sb.append(" - Número de Consultas Facturadas: ").append(consultas).append("\n");
                sb.append(" - Total de Facturas Emitidas: ").append(facturasEmitidas).append("\n\n");
            }
        }
        produccionArea.setText(sb.toString());
    }//GEN-LAST:event_reporteProduccionButtonActionPerformed

    private void inicioIngresosFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioIngresosFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inicioIngresosFieldActionPerformed

    private void finIngresosFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finIngresosFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finIngresosFieldActionPerformed

    private void reporteIngresosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteIngresosButtonActionPerformed
        String fechaInicio = inicioIngresosField.getText();
        String fechaFin = finIngresosField.getText();

        double totalIngresos = 0;
        double ingresosPorConsultas = 0;
        double ingresosPorServicios = 0;

        for (Factura f : gestionFacturacion.getFacturas()) {
            boolean enRango = (fechaInicio.isEmpty() || f.getFecha().compareTo(fechaInicio) >= 0)
                    && (fechaFin.isEmpty() || f.getFecha().compareTo(fechaFin) <= 0);

            if (enRango) {
                totalIngresos += f.getTotal();
                ingresosPorConsultas += GestionFacturacion.getPRECIO_CONSULTA();
                ingresosPorServicios += (f.getTotal() - GestionFacturacion.getPRECIO_CONSULTA());
            }
        }

        StringBuilder sb = new StringBuilder("--- Reporte de Ingresos ---\n");
        if (!fechaInicio.isEmpty() && !fechaFin.isEmpty()) {
            sb.append("Periodo: ").append(fechaInicio).append(" al ").append(fechaFin).append("\n\n");
        }
        sb.append(String.format("Ingreso Total General: $%.2f\n\n", totalIngresos));
        sb.append("Desglose por Tipo de Servicio:\n");
        sb.append(String.format(" - Ingresos por Consultas: $%.2f\n", ingresosPorConsultas));
        sb.append(String.format(" - Ingresos por Servicios Adicionales (Lab/Imagen/Etc): $%.2f\n", ingresosPorServicios));

        ingresosArea.setText(sb.toString());
    }//GEN-LAST:event_reporteIngresosButtonActionPerformed

    private void reporteOcupacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteOcupacionButtonActionPerformed
        String fecha = ocupacionFechaField.getText();
        if (fecha.isEmpty()) {
            JOptionPane.showMessageDialog(reporteOcupacionPanel, "Por favor, ingrese una fecha.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        StringBuilder sb = new StringBuilder();
        sb.append("--- Reporte de Ocupación para la fecha: ").append(fecha).append(" ---\n\n");

        ArrayList<Cita> citasDelDia = gestionCitas.buscarCitaPorFecha(fecha);
        ArrayList<Consultorio> todosLosConsultorios = gestionConsultorios.getConsultorios();

        for (Consultorio cons : todosLosConsultorios) {
            sb.append("Consultorio ").append(cons.getCodigo()).append(" (").append(cons.getEspecialidad()).append("):\n");
            boolean ocupadoEnAlgunMomento = false;
            for (Cita cita : citasDelDia) {
                if (cita.getConsultorio().equals(cons)) {
                    sb.append("  - Ocupado a las ").append(cita.getFechaHora().substring(11)).append(" por Dr. ").append(cita.getMedico().getApellidos()).append("\n");
                    ocupadoEnAlgunMomento = true;
                }
            }
            if (!ocupadoEnAlgunMomento) {
                sb.append("  - No tuvo citas programadas para esta fecha.\n");
            }
            sb.append("\n");
        }
        ocupacionArea.setText(sb.toString());
    }//GEN-LAST:event_reporteOcupacionButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField finIngresosField;
    private javax.swing.JTextField finProduccionField;
    private javax.swing.JTextArea ingresosArea;
    private javax.swing.JTextField inicioIngresosField;
    private javax.swing.JTextField inicioProduccionField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea ocupacionArea;
    private javax.swing.JTextField ocupacionFechaField;
    private javax.swing.JTextArea produccionArea;
    private javax.swing.JButton reporteIngresosButton;
    private javax.swing.JPanel reporteIngresosPanel;
    private javax.swing.JButton reporteOcupacionButton;
    private javax.swing.JPanel reporteOcupacionPanel;
    private javax.swing.JButton reporteProduccionButton;
    private javax.swing.JPanel reporteProduccionPanel;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
